### ISSUE TITLE
RabbitMQ messages limited to 64MiB

### ISSUE THREAD

**Issue by robbavey** [logstash-plugins/logstash-integration-rabbitmq#59]
Attempting to receive messages greater than 64MiB from a RabbitMQ queue, will currently fail with the following error:

```
[2024-04-28T13:11:12,192][ERROR][com.rabbitmq.client.impl.ForgivingExceptionHandler][err][rabbitmq] An unexpected connection driver error occurred
java.lang.IllegalStateException: Message body is too large (103456140), maximum configured size is 67108864. See ConnectionFactory#setMaxInboundMessageBodySize if you need to increase the limit.
at com.rabbitmq.client.impl.CommandAssembler.consumeHeaderFrame(CommandAssembler.java:109) ~[rabbitmq-client.jar:5.20.0]
at com.rabbitmq.client.impl.CommandAssembler.handleFrame(CommandAssembler.java:172) ~[rabbitmq-client.jar:5.20.0]
at com.rabbitmq.client.impl.AMQCommand.handleFrame(AMQCommand.java:108) ~[rabbitmq-client.jar:5.20.0]
at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:123) ~[rabbitmq-client.jar:5.20.0]
at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:761) [rabbitmq-client.jar:5.20.0]
at com.rabbitmq.client.impl.AMQConnection.access$400(AMQConnection.java:48) [rabbitmq-client.jar:5.20.0]
at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:688) [rabbitmq-client.jar:5.20.0]
at java.lang.Thread.run(Thread.java:829) [?:?]
```

This error effectively blocks the queue from being processed by Logstash, with the message acting as a "poison pill"

**Comment by robbavey** [comment]
Related: https://github.com/ruby-amqp/march_hare/pull/164
